services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - /code/node_modules
      - /code/.next
      - ./frontend:/code
  backend:
    depends_on:
      - database
      - cache
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
  worker:
    depends_on:
      - database
      - cache
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
    command: poetry run python manage.py ovum_rundramatiq
  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
  cache:
    image: valkey/valkey:8
  caddy:
    image: caddy:2
    ports:
      - 3000:3000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  # storage:
