services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - /code/node_modules
      - /code/.next
      - ./frontend:/code
  backend:
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
  worker:
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/code
    command: poetry run python manage.py ovum_rundramatiq
  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  cache:
    image: valkey/valkey:8
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  caddy:
    image: caddy:2
    ports:
      - 3000:3000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  # storage:
