[mypy]
check_untyped_defs = True
disallow_untyped_defs = True
warn_return_any = True
show_error_codes = True
warn_unused_ignores = True

exclude = (?x)(
    ^manage.py$               # Django-generated management script comes with no types
    | ^gunicorn.conf.py$      # gunicorn config uses monkeypatching, which types poorly
  )
plugins =
    ./configurations_mypy_plugin.py,mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "backend.settings"

# Stubs don't yet exist for these modules
[mypy-environ]
ignore_missing_imports = True

[mypy-configurations.*]
ignore_missing_imports = True
