/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Ovum API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "./mutator/custom-instance";
export type ApiSchemaRetrieveParams = {
  format?: ApiSchemaRetrieveFormat;
  lang?: ApiSchemaRetrieveLang;
};

export type ApiSchemaRetrieveFormat =
  (typeof ApiSchemaRetrieveFormat)[keyof typeof ApiSchemaRetrieveFormat];

export const ApiSchemaRetrieveFormat = {
  json: "json",
  yaml: "yaml",
} as const;

export type ApiSchemaRetrieveLang =
  (typeof ApiSchemaRetrieveLang)[keyof typeof ApiSchemaRetrieveLang];

export const ApiSchemaRetrieveLang = {
  af: "af",
  ar: "ar",
  arDz: "ar-dz",
  ast: "ast",
  az: "az",
  be: "be",
  bg: "bg",
  bn: "bn",
  br: "br",
  bs: "bs",
  ca: "ca",
  ckb: "ckb",
  cs: "cs",
  cy: "cy",
  da: "da",
  de: "de",
  dsb: "dsb",
  el: "el",
  en: "en",
  enAu: "en-au",
  enGb: "en-gb",
  eo: "eo",
  es: "es",
  esAr: "es-ar",
  esCo: "es-co",
  esMx: "es-mx",
  esNi: "es-ni",
  esVe: "es-ve",
  et: "et",
  eu: "eu",
  fa: "fa",
  fi: "fi",
  fr: "fr",
  fy: "fy",
  ga: "ga",
  gd: "gd",
  gl: "gl",
  he: "he",
  hi: "hi",
  hr: "hr",
  hsb: "hsb",
  ht: "ht",
  hu: "hu",
  hy: "hy",
  ia: "ia",
  id: "id",
  ig: "ig",
  io: "io",
  is: "is",
  it: "it",
  ja: "ja",
  ka: "ka",
  kab: "kab",
  kk: "kk",
  km: "km",
  kn: "kn",
  ko: "ko",
  ky: "ky",
  lb: "lb",
  lt: "lt",
  lv: "lv",
  mk: "mk",
  ml: "ml",
  mn: "mn",
  mr: "mr",
  ms: "ms",
  my: "my",
  nb: "nb",
  ne: "ne",
  nl: "nl",
  nn: "nn",
  os: "os",
  pa: "pa",
  pl: "pl",
  pt: "pt",
  ptBr: "pt-br",
  ro: "ro",
  ru: "ru",
  sk: "sk",
  sl: "sl",
  sq: "sq",
  sr: "sr",
  srLatn: "sr-latn",
  sv: "sv",
  sw: "sw",
  ta: "ta",
  te: "te",
  tg: "tg",
  th: "th",
  tk: "tk",
  tr: "tr",
  tt: "tt",
  udm: "udm",
  ug: "ug",
  uk: "uk",
  ur: "ur",
  uz: "uz",
  vi: "vi",
  zhHans: "zh-hans",
  zhHant: "zh-hant",
} as const;

export type ApiSchemaRetrieve200One = { [key: string]: unknown };

export type ApiSchemaRetrieve200Two = { [key: string]: unknown };

export type ApiSchemaRetrieve200Three = { [key: string]: unknown };

export type ApiSchemaRetrieve200Four = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.

- YAML: application/vnd.oai.openapi
- JSON: application/vnd.oai.openapi+json
 */
export const apiSchemaRetrieve = (
  params?: ApiSchemaRetrieveParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<
    | ApiSchemaRetrieve200One
    | ApiSchemaRetrieve200Two
    | ApiSchemaRetrieve200Three
    | ApiSchemaRetrieve200Four
  >({ url: `/api/schema/`, method: "GET", params, signal }, options);
};

export const getApiSchemaRetrieveQueryKey = (
  params?: ApiSchemaRetrieveParams,
) => {
  return [`/api/schema/`, ...(params ? [params] : [])] as const;
};

export const getApiSchemaRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiSchemaRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiSchemaRetrieveQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiSchemaRetrieve>>
  > = ({ signal }) => apiSchemaRetrieve(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiSchemaRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ApiSchemaRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiSchemaRetrieve>>
>;
export type ApiSchemaRetrieveQueryError = unknown;

export function useApiSchemaRetrieve<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params: undefined | ApiSchemaRetrieveParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiSchemaRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiSchemaRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiSchemaRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiSchemaRetrieve<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiSchemaRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiSchemaRetrieve>>,
          TError,
          Awaited<ReturnType<typeof apiSchemaRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiSchemaRetrieve<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiSchemaRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useApiSchemaRetrieve<
  TData = Awaited<ReturnType<typeof apiSchemaRetrieve>>,
  TError = unknown,
>(
  params?: ApiSchemaRetrieveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiSchemaRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getApiSchemaRetrieveQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
