name: Lint

on: push

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry && poetry install
      - run: poetry run ruff check .
      - run: poetry run ruff format --check .

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      DJANGO_CONFIGURATION: Local
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry && poetry install
      - run: poetry run mypy .
